######################################################
##
##   本地测试环境配置文件
##
######################################################

# 日志配置
LOG:
  # 控制台log级别，从低到高包含DEBUG、INFO、WARN、ERROR、CRITICAL。
  LOG_LEVEL: DEBUG
  # log保存路径
  LOG_FOLDER: ./logs
  # log文件名称，默认为service.Log
  LOG_FILENAME: service.log
  # 日志文件记录的级别个数（1～5），从低到高计数。
  BACKUPCOUNT: 5

# 网络配置
SERVER:
  IP: 0.0.0.0
  PORT: 10007
  WORKERS: 1

# 启动哪个子服务（teacher: 助教进行个性化路径规划; quiz: 进行计算机自适应测试； full_run：同时启动所有服务 ）
SERVICE_NAME:
  NAME: full_run  # 支持配置的字段有 teacher / quiz /full_run

# LLM配置
LLM:
  MODEL_NAME: "qwen-plus-latest"
  API_KEY_NAME: "BAILIAN_API_KEY" # 把你的api_key设置进你的电脑环境变量，环境变量名称为BAILIAN_API_KEY
  BASE_URL: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  OPENAI_HEADERS: { "Authorization": "Bearer sk-e2301e1702874ea397fced79897a3da6",
                    "User-Agent": "Apifox/1.0.0 (https://apifox.com)",
                    "Content-Type": "application/json" }


SELECT_SERVER:
  ENTERPRISE_URL: "http://10.78.160.115:80/paas-gateway/grid-task/build/Ai/getEnterpriseInfo"
  ESOP_ENTERPRISE_URL: "http://10.78.160.115:80/paas-gateway/grid-task/build/Ai/getEsopEnterpriseInfo"
  HUAXIANG_URL: "http://10.78.160.115:80/paas-gateway/griddiffusermarketservice/zqView/getGroupHxInfo2"



# 会话管理的参数
SESSION:
  SESSION_TIMEOUT: 1800 # 1h   # 暂时未使用

# 学生相关信息
STUDENT:
  START_NUMBER: 1 # 第几个学生开始执行
  END_NUMBER: 1 # 第几个学生结束执行
  PLPP_SAVE_PATH: "data/student_learning_paths.csv" # plpp保存路径

# CAT相关相信
CAT:
  INIT_DIFFICULTY: "medium"   # 初始难度级别（下面的参数要统一：easy是1-3，medium是4-7，hard是8-10）
  INIT_DIFFICULTY_LEVEL: 5 # 初始难度级别（上面的参数要统一：easy是1-3，medium是4-7，hard是8-10）
  TOTAL_QUESTIONS: 20 # 题目总数
