######################################################
##
##   本地测试环境配置文件
##
######################################################

# 日志配置
LOG:
  # 控制台log级别，从低到高包含DEBUG、INFO、WARN、ERROR、CRITICAL。
  LOG_LEVEL: DEBUG
  # log保存路径
  LOG_FOLDER: ./logs
  # log文件名称，默认为service.Log
  LOG_FILENAME: service.log
  # 日志文件记录的级别个数（1～5），从低到高计数。
  BACKUPCOUNT: 5

# 网络配置
SERVER:
  IP: 0.0.0.0
  PORT: 10007
  WORKERS: 1

# LLM配置
LLM:
  MODEL_NAME: "qwen-plus-latest"
  API_KEY: "输入你自己的api-key，并将本文件名改成config.yaml"
  BASE_URL: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  OPENAI_HEADERS: { "Authorization": "Bearer sk-e2301e1702874ea397fced79897a3da6",
                    "User-Agent": "Apifox/1.0.0 (https://apifox.com)",
                    "Content-Type": "application/json" }


SELECT_SERVER:
  ENTERPRISE_URL: "http://10.78.160.115:80/paas-gateway/grid-task/build/Ai/getEnterpriseInfo"
  ESOP_ENTERPRISE_URL: "http://10.78.160.115:80/paas-gateway/grid-task/build/Ai/getEsopEnterpriseInfo"
  HUAXIANG_URL: "http://10.78.160.115:80/paas-gateway/griddiffusermarketservice/zqView/getGroupHxInfo2"



# 会话管理的参数
SESSION:
  SESSION_TIMEOUT: 1800 # 1h   # 暂时未使用

# 学生相关信息
STUDENT:
  START_NUMBER: 1 # 第几个学生开始执行
  END_NUMBER: 10 # 第几个学生结束执行
  PLPP_SAVE_PATH: "data/student_learning_paths.csv" # plpp保存路径